site_name: Smelter Optimisation Assignment

theme:
  name: "material"

nav:
  - Home: index.md
  - API Reference:
    - Solver: api_reference/solver.md
    - Models: api_reference/models.md
    - Neighbourhood Rule: api_reference/neighbourhood.md
    - Utils: api_reference/utils.md
  
plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [smelter_optimisation]  # search packages here
        options:
          docstring_style: google
          show_docstring_examples: true

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences  

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js