site_name: Smelter Optimisation Assignment

theme:
  name: "material"

nav:
  - Home: index.md
  - Code Reference:
    - Solver: solver.md
    - Models: models.md
    - Neighbourhood Rule: neighbourhood.md
    - Utils: utils.md
  
plugins:
- mkdocstrings:
    handlers:
      python:
        paths: [smelter_optimisation]  # search packages here
        options:
          docstring_style: sphinx
          show_docstring_examples: true

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js